import { fileRole, kindOfPath } from "@pd/analyzer/classify";
import type { FileKind } from "@pd/analyzer";
import type { EditScope } from "./edit-schema";
import { isRepoPath, TEST_PATH, type RepositoryFacts, type ValidatedPlan } from "./validate";

/**
 * What the code engine may touch. The approved plan defines the scope; a fixed set
 * of paths is never editable whatever the plan says, because changing them could
 * run code, leak or replace credentials, or change how the project is built and
 * deployed outside the reviewed source.
 */

export const EDIT_LIMITS = {
  /** Files shown to the model, bytes per file and in total. */
  contextFiles: 20,
  contextFileBytes: 64 * 1024,
  contextBytes: 400 * 1024,
  /** Accepted changes per iteration and changed (added + removed) lines in total. */
  changes: 30,
  changedLines: 2000,
  /** Size of a file after the change. */
  resultFileBytes: 256 * 1024,
  /** Prose fields (summary, reasons, notes). */
  text: 2000,
  notes: 20,
} as const;

const GIT_CONFIG_FILE = /^\.(?:gitattributes|gitmodules)$/;
const HOOK_PATH = /(?:^|\/)\.(?:husky|githooks)\/|(?:^|\/)(?:lefthook\.ya?ml|\.pre-commit-config\.yaml)$/i;
const CI_PATH = /(?:^|\/)\.github\//;
/** Package-manager configuration that can redirect registries or run code during installs. */
const PACKAGE_MANAGER_CONFIG = /^(?:\.yarnrc(?:\.yml)?|\.pnpmfile\.c?js|bunfig\.toml|pip\.conf|\.condarc)$/;

const base = (p: string) => p.slice(p.lastIndexOf("/") + 1);

/** Why the code engine must never change this path, or null when it may (within scope). */
export function forbiddenReason(path: string, kind: FileKind = kindOfPath(path)): string | null {
  if (path.split("/").includes(".git")) return "Git metadata";
  if (GIT_CONFIG_FILE.test(base(path))) return "Git configuration (attributes and submodules can run filters or fetch code)";
  if (HOOK_PATH.test(path)) return "Git hook configuration";
  if (CI_PATH.test(path)) return "CI configuration";
  if (PACKAGE_MANAGER_CONFIG.test(base(path))) return "package-manager configuration";
  switch (fileRole(path, kind)) {
    case "secret":
      return "a file that holds secrets";
    case "lockfile":
      return "a lockfile (regenerated by the package manager, never edited)";
    case "infrastructure":
      return "CI, container or deployment configuration";
    case "binary":
      return "a binary file";
    default:
      return null;
  }
}

/** Secret files are never shown to the model, not even for reference. */
export const isSecretPath = (path: string, kind?: FileKind) => fileRole(path, kind ?? kindOfPath(path)) === "secret";

const UNUSABLE = new Set(["invalid-path", "nonexistent-file"]);
const usable = (flags: string[]) => !flags.some((f) => UNUSABLE.has(f));

/**
 * The files an approved plan lets the code engine change. Items the plan's
 * validation flagged as invalid or nonexistent are excluded, and so is every
 * forbidden path, whatever the plan says.
 */
export function deriveEditScope(plan: ValidatedPlan, facts: RepositoryFacts): EditScope {
  const exists = (p: string) => facts.files.has(p);
  const allowed = (p: string) => isRepoPath(p) && forbiddenReason(p, facts.files.get(p)) === null;
  const modify = new Set<string>();
  const create = new Set<string>();
  const del = new Set<string>();

  for (const f of plan.affectedFiles) {
    if (!usable(f.flags)) continue;
    if (f.change === "modify" && exists(f.path)) modify.add(f.path);
    if (f.change === "delete" && exists(f.path)) del.add(f.path);
    if (f.change === "create" && !exists(f.path)) create.add(f.path);
  }
  for (const s of plan.affectedSymbols) {
    if (s.change === "modify" && !s.flags.includes("invalid-path") && exists(s.path)) modify.add(s.path);
  }
  for (const t of plan.testPlan) {
    if (!t.path || t.flags.includes("invalid-path")) continue;
    if (t.kind === "existing" && facts.files.get(t.path) === "TEST") modify.add(t.path);
    if (t.kind === "new" && !exists(t.path) && TEST_PATH.test(t.path)) create.add(t.path);
  }
  for (const c of plan.configurationChanges) {
    if (c.flags.includes("invalid-path")) continue;
    (exists(c.path) ? modify : create).add(c.path);
  }
  const sorted = (s: Set<string>) => [...s].filter(allowed).sort();
  return {
    modify: sorted(modify),
    create: sorted(create),
    delete: sorted(del).filter((p) => !modify.has(p)),
    newTests: true,
    dependencyChanges: plan.dependencyChanges.some((d) => d.change !== "none"),
  };
}
